/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d5086409-db6c-4d6f-930f-73bdc6be6666",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vlJgfTDq0",
    "aws_user_pools_web_client_id": "5dd375295132n4iq08og4qajka",
    "oauth": {}
};


export default awsmobile;
