/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:d5086409-db6c-4d6f-930f-73bdc6be6666",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_vlJgfTDq0",
    "aws_user_pools_web_client_id": "5dd375295132n4iq08og4qajka",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xf4czg6hzfdtpayfw5d4spdlu4.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-kiw2ndxppbbudnjq27svpr5i7i"
};


export default awsmobile;
