const backgroundImage = {
    type: "image",
    version: "4.2.0",
    originX: "left",
    originY: "top",
    left: 0,
    top: 0,
    width: 3060,
    height: 1980,
    fill: "rgb(0,0,0)",
    stroke: null,
    strokeWidth: 0,
    strokeDashArray: null,
    strokeLineCap: "butt",
    strokeDashOffset: 0,
    strokeLineJoin: "miter",
    strokeMiterLimit: 4,
    scaleX: 1,
    scaleY: 1,
    angle: 0,
    flipX: false,
    flipY: false,
    opacity: 1,
    shadow: null,
    visible: true,
    backgroundColor: "",
    fillRule: "nonzero",
    paintFirst: "fill",
    globalCompositeOperation: "source-over",
    skewX: 0,
    skewY: 0,
    cropX: 0,
    cropY: 0,
    src: "https://triumphdespair.files.wordpress.com/2012/11/range-bands.jpg",
    crossOrigin: null,
    filters: []
};

export default backgroundImage