const speciesList = [
    "--Please Select--",
    "Aleena",
    "Anx",
    "Aqualish (Aquala)",
    "Aqualish (Quara)",
    "Aqualish (Ualaq)",
    "Arcona",
    "Arkanian",
    "Bardottan",
    "Besalisk",
    "Bothan",
    "Caamasi",
    "Cerean",
    "Chadra-Fan",
    "Chagrian",
    "Chevin",
    "Chiss",
    "Clawdite",
    "Clone",
    "Corellian Human",
    "Cosian",
    "Dathomirian",
    "Devaronian",
    "Dowutin",
    "Drall",
    "Dressellian (Primitive)",
    "Dressellian (Non-Primitive)",
    "Droid",
    "Dug",
    "Duros",
    "Elom",
    "Elomin",
    "Ewok",
    "Falleen",
    "Gand (With Lungs)",
    "Gand (Without Lungs)",
    "Gank",
    "Geonosian",
    "Gigoran",
    "Gossam",
    "Gotal",
    "Gran",
    "Gungan",
    "Harch",
    "Human",
    "Hutt",
    "Iakaru",
    "Iktotchi",
    "Ishi Tib",
    "Kyuzo",
    "Lannik",
    "Lasat",
    "Mandalorian Human",
    "Melitto",
    "Mikkian",
    "Mirialan",
    "Mon Calamari",
    "Mustafarian (Northern)",
    "Mustafarian (Southern)",
    "Muun",
    "Nautolan",
    "Neimodian",
    "Nikto (Green)",
    "Nikto (Mountain)",
    "Nikto (Pale)",
    "Nikto (Red)",
    "Nikto (Southern)",
    "Pantoran",
    "Pau'an",
    "Phydolon",
    "Polis Massan (With Vocal Chords)",
    "Polis Massan (Without Vocal Chords)",
    "Quarren",
    "Quermian",
    "Rodian",
    "Sakiyan",
    "Sathari",
    "Selonian",
    "Shistavanen",
    "Skakoans",
    "Sullustan",
    "Thisspiasian",
    "Tholothian",
    "Tognath",
    "Togruta",
    "Toydarian",
    "Trandosian",
    "Tusken Raider",
    "Twi'lek",
    "Umbaran",
    "Verpine",
    "Vurk",
    "Weequay",
    "Whiphid",
    "Wookiee",
    "Xexto",
    "Zabrak",
];

export default speciesList