const specializations = {
    "": ["--Please Select--"],
    "Bounty Hunter": [
        "Assassin",
        "Gadgeteer",
		"Martial Artist",
		"Operator",
		"Skip Tracer",
        "Survivalist",
    ],
    "Colonist": [
        "Doctor",
        "Politico",
        "Scholar",
        "Entrepreneur",
        "Marshal",
        "Performer"
    ],
    "Explorer": [
        "Scout",
        "Fringer",
        "Driver",
        "Archaeologist",
        "Big-Game Hunter",
        "Trader"
    ],
    "Hired Gun": [
        "Bodyguard",
        "Demolitionist",
        "Enforcer",
        "Heavy",
        "Marauder",
        "Mercenary Soldier"
    ],
    "Smuggler": [
        "Pilot",
        "Scoundrel",
        "Thief",
        "Charmer",
        "Gambler",
        "Gunslinger",
    ],
    "Technician": [
        "Mechanic",
        "Outlaw Tech",
        "Slicer",
        "Cyber Tech",
        "Droid Tech",
        "Modder",
    ],
    "Ace": [
        "Driver",
        "Pilot",
        "Gunner",
        "Rigger",
        "Hotshot",
        "Beast Rider",
    ],
    "Commander": [
        "Commodore",
        "Squadron Leader",
        "Tactician",
        "Figurehead",
        "Instructor",
        "Strategist",
    ],
    "Diplomat": [
        "Ambassador",
        "Agitator",
        "Quartermaster",
        "Analyst",
        "Advocate",
        "Propagandist",
    ],
    "Engineer": [
        "Droid Specialist",
        "Mechanic",
		"Saboteur",
		"Sapper",
        "Scientist",
        "Shipwright",
    ],
    "Soldier": [
        "Medic",
        "Sharpshooter",
        "Commando",
		"Heavy",
		"Trailblazer",
		"Vanguard",
    ],
    "Spy": [
        "Courier",
        "Infiltrator",
        "Interrogator",
        "Scout",
        "Sleeper Agent",
        "Slicer",
    ],
    "Consular": [
        "Arbiter",
        "Ascetic",
        "Healer",
        "Niman Disciple",
        "Sage",
        "Teacher",
    ],
    "Guardian": [
        "Armorer",
        "Peace Keeper",
        "Protector",
        "Soresu Defender",
        "Warden",
        "Warleader",
    ],
    "Mystic": [
        "Advisor",
        "Alchemist",
        "Magus",
        "Makashi Duelist",
        "Prophet",
        "Seer",
    ],
    "Seeker": [
        "Ataru Striker",
        "Executioner",
        "Hermit",
        "Hunter",
        "Navigator",
        "Pathfinder",
    ],
    "Sentinel": [
        "Artisan",
        "Investigator",
        "Racer",
        "Sentry",
        "Shadow",
        "Shien Expert",
    ],
    "Warrior": [
        "Aggressor",
        "Colossus",
        "Juyo Berserker",
        "Shii-Cho Knight",
        "Starfighter Ace",
        "Steel Hand Adept",
    ],
    "Clone Soldier": [
        "Clone Trooper",
        "Clone Pilot",
        "Clone Officer",
        "ARC Trooper",
        "Clone Commander",
        "Clone Veteran",
    ],
    "Jedi": [
        "Padawan",
        "Knight",
        "General",
        "Master",
    ],
    "Universal": [
        "Death Watch Warrior",
        "Force Adherent",
        "Force Sensitive Emergent",
        "Force Sensitive Exile",
        "Force Sensitive Outcast",
        "Imperial Academy Cadet",
        "Nightsister",
        "Padawan Survivor",
        "Pirate",
        "Recruit",
        "Republic Navy Officer",
        "Republic Representative",
        "Retired Clone Trooper",
        "Scavenger",
        "Senator",
        "Separatist Commander",
        "Ship Captain",
    ],
};

export default specializations
